#!/bin/sh

# Just for test
buildNo=$(git rev-list --count main)
message=$(cat $1)
version=$(cat VERSION)

echo buildNo > BUILD
echo "$version.$buildNo - $message" >> CHANGELOG

git add BUILD
git add CHANGELOG

exit 0