#!/bin/sh

buildNo=$(git rev-list --count main)
echo "Set Build # "$buildNo

sed -i 's/{{build}}/'"${buildNo}"'/' CHANGELOG.md
sed -i 's/{{now}}/'"$(date '+%Y-%m-%d')"'/' CHANGELOG.md

git add CHANGELOG.md

exit 0